# --- represents this file as a playbook
---
# Use [space]play[space] where play is combination of hosts+tasks
- name: "Playbook to create a file and a directory"
  hosts: all
  # Become root user
  become: yes
  # variables
  vars:
    - filename: supu.txt
    - dirname: lovesupu
  # List of tasks to be execute
  tasks:
    - name: print variables
      debug:
        msg: "Filename: {{ filename }}, Directory name: {{ dirname }}"

    - name: "just print what is there and in what condition"
      shell: "ls -lrt /etc"
      register: "output"

    - debug: var=output.stdout_lines

    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      ansible.builtin.file:
        path: /etc/{{ filename }}
        state: touch
        mode: u=rw,g=r,o=r

    - name: Touch the same file, but add/remove some permissions
      ansible.builtin.file:
        path: /etc/{{ filename }}
        state: touch
        mode: u+rw,g-wx,o-rwx

    - name: Touch again the same file, but do not change times this makes the task idempotent
      ansible.builtin.file:
        path: /etc/{{ filename }}
        state: touch
        mode: u+rw,g-wx,o-rwx
        modification_time: preserve
        access_time: preserve

    - name: "just print what is there and in what condition"
      shell: "ls -lrt /etc"
      register: "output"

    - debug: var=output.stdout_lines

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/{{ dirname }}
        state: directory
        mode: "0755"

    - name: Update modification and access time of given file
      ansible.builtin.file:
        path: /etc/{{ filename }}
        state: file
        modification_time: now
        access_time: now

    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /etc/{{ filename }}
        state: absent
