# --- represents this file as a playbook
---
# Use [space]play[space] where play is combination of hosts+tasks
- name: "Playbook to execute find command on all hosts"
  hosts: all
  # Become root user
  become: yes
  # List of tasks to be execute
  tasks:
    - name: "just execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output"

    - debug: var=output.stdout_lines

    - name: Recursively find /tmp files older than 2 days
      ansible.builtin.find:
        paths: /tmp
        age: 2d
        recurse: yes

    - name: Recursively find /tmp files older than 4 weeks and equal or greater than 1 megabyte
      ansible.builtin.find:
        paths: /tmp
        age: 4w
        size: 1m
        recurse: yes

    - name: Recursively find /var/tmp files with last access time greater than 3600 seconds
      ansible.builtin.find:
        paths: /var/tmp
        age: 3600
        age_stamp: atime
        recurse: yes

    - name: Find /var/log files equal or greater than 10 megabytes ending with .old or .log.gz
      ansible.builtin.find:
        paths: /var/log
        patterns: "*.old,*.log.gz"
        size: 10m

    # Note that YAML double quotes require escaping backslashes but yaml single quotes do not.
    - name: Find /var/log files equal or greater than 10 megabytes ending with .old or .log.gz via regex
      ansible.builtin.find:
        paths: /var/log
        patterns: "^.*?\\.(?:old|log\\.gz)$"
        size: 10m
        use_regex: yes

    - name: Find /var/log all directories, exclude nginx
      ansible.builtin.find:
        paths: /var/log
        recurse: no
        file_type: directory
        excludes: "nginx"

    # When using patterns that contain a comma, make sure they are formatted as lists to avoid splitting the pattern
    - name: Use a single pattern that contains a comma formatted as a list
      ansible.builtin.find:
        paths: /var/log
        file_type: file
        use_regex: yes
        patterns: ["^_[0-9]{2,4}_.*.log$"]

    - name: Use multiple patterns that contain a comma formatted as a YAML list
      ansible.builtin.find:
        paths: /var/log
        file_type: file
        use_regex: yes
        patterns:
          - "^_[0-9]{2,4}_.*.log$"
          - "^[a-z]{1,5}_.*log$"
