- name: Ansible magic variables
  hosts: all
  gather_facts: true
  tasks:
   - name: Magic varibale use
     ansible.builtin.debug:
       var: "{{ item }}"
     loop:
        - ansible_config_file
        - playbook_dir
        - inventory_dir
        - inventory_file
        - ansible_check_mode
        - ansible_diff_mode
        - ansible_forks
        - ansible_verbosity
        - ansible_hostname
        - ansible_play_hosts
        - ansible_version
